In [93]:
import math
import numpy as np
from random import randint, randrange, uniform
from numba import jit, njit,prange, vectorize, cuda, guvectorize, float64

In [77]:
issycodes = 5
dig16codes = 12
factors = 8
elms = 4

## cdf LC arrays

In [78]:
arcr = np.full(shape=(dig16codes,factors),fill_value=-1,dtype=np.int32)
arfac = np.zeros(shape=(dig16codes,factors),dtype=np.float32)

In [79]:
for i in range(dig16codes):
    no_lcs = randrange(factors)
    for j in range(no_lcs):
        arcr[i,j] = randrange(issycodes)# + 501
        arfac[i,j] = uniform(-1.0, 1.5)
arcr

array([[-1, -1, -1, -1, -1, -1, -1, -1],
       [ 3,  1,  4,  3,  0,  3, -1, -1],
       [ 4,  2,  1,  4, -1, -1, -1, -1],
       [ 3,  3,  0, -1, -1, -1, -1, -1],
       [ 1,  1,  2, -1, -1, -1, -1, -1],
       [ 3,  2, -1, -1, -1, -1, -1, -1],
       [ 3,  4,  2,  0,  4,  4, -1, -1],
       [ 0,  3,  2,  1,  2,  1, -1, -1],
       [ 1,  4,  4,  1,  4, -1, -1, -1],
       [ 0,  0,  4, -1, -1, -1, -1, -1],
       [ 4,  2, -1, -1, -1, -1, -1, -1],
       [ 2,  2,  0, -1, -1, -1, -1, -1]], dtype=int32)

## fue array

In [84]:
arfue =  np.random.rand(issycodes,elms,3).astype(np.float32) * 100
arfue

array([[[73.64337 , 12.153724, 49.068592],
        [92.32045 , 44.503586, 70.06611 ],
        [76.33129 , 10.493861, 49.01697 ],
        [12.466313, 21.686707, 91.93686 ]],

       [[68.76658 , 10.826293, 92.23863 ],
        [68.04789 , 39.838867, 59.31694 ],
        [ 6.774627, 32.68123 , 40.111313],
        [93.01114 , 60.631474, 85.88425 ]],

       [[71.595535, 18.046595, 41.185318],
        [95.03198 , 99.7255  , 57.62417 ],
        [30.428331, 90.94328 , 98.33628 ],
        [13.065786, 63.70038 , 94.773506]],

       [[27.807035, 57.60954 , 29.14085 ],
        [53.76022 , 68.63951 , 94.69003 ],
        [58.081238, 27.800068, 55.312496],
        [91.05415 , 18.249157, 84.992775]],

       [[45.8591  , 17.654049, 95.74351 ],
        [73.45729 , 79.8225  , 38.556572],
        [98.19757 , 36.114574, 69.12599 ],
        [19.32543 , 76.30962 , 98.7514  ]]], dtype=float32)

## numba array mult

In [85]:
@njit
def create_clc(arcr):
    pass

In [96]:
@vectorize([float64(float64, float64,float64, float64)])
def transform2d(sx,sy,sxy,angle):
    arad = math.radians(angle)
    return (sx+sy)* 0.5 + (sx-sy) * 0.5 * math.cos(2*arad) + sxy * math.sin(2*arad)
    

In [87]:
ar_el = arfue[:,1,:]
ar_el


array([[92.32045 , 44.503586, 70.06611 ],
       [68.04789 , 39.838867, 59.31694 ],
       [95.03198 , 99.7255  , 57.62417 ],
       [53.76022 , 68.63951 , 94.69003 ],
       [73.45729 , 79.8225  , 38.556572]], dtype=float32)

In [98]:
transform2d(ar_el,10)

ValueError: invalid number of arguments